-- Run this once in the Supabase SQL Editor.
-- The Cloudflare Worker writes with the secret/service-role key; that key stays server-side.

create table if not exists public.website_enquiries (
  id bigint generated by default as identity primary key,
  form_type text not null default 'contact',
  full_name text not null,
  email text not null,
  phone text,
  enquiry_type text,
  message text not null,
  consent boolean not null default false,
  submitted_at timestamptz not null default now(),
  user_agent text
);

create table if not exists public.website_join_interest (
  id bigint generated by default as identity primary key,
  form_type text not null default 'join-us',
  full_name text not null,
  email text not null,
  phone text,
  location text,
  role text,
  expertise text,
  qualification text,
  registration text,
  profile_url text,
  message text not null,
  consent boolean not null default false,
  submitted_at timestamptz not null default now(),
  user_agent text
);

alter table public.website_enquiries enable row level security;
alter table public.website_join_interest enable row level security;

create table if not exists public.website_beyond_interest (
  id bigint generated by default as identity primary key,
  form_type text not null default 'lutsha-beyond',
  full_name text not null,
  email text not null,
  phone text,
  country text,
  organisation text,
  audience text,
  interest_area text,
  message text not null,
  consent boolean not null default false,
  submitted_at timestamptz not null default now(),
  user_agent text
);

alter table public.website_beyond_interest enable row level security;

create index if not exists website_beyond_interest_submitted_at_idx
  on public.website_beyond_interest (submitted_at desc);
